export const ACTION_TYPES = {
    
    //Consultants
    FETCH_ALL_CONSULTANTS: 'FETCH_ALL_CONSULTANTS',
    GET_CONSULTANT: "GET_CONSULTANT",
    CREATE_CONSULTANT: 'CREATE_CONSULTANT',
    UPDATE_CONSULTANT: 'UPDATE_CONSULTANT',
    DELETE_CONSULTANT: 'DELETE_CONSULTANT',

    //Sales
    FETCH_ALL_SALES: 'FETCH_ALL_SALES',
    CREATE_SALE: 'CREATE_SALE',
    UPDATE_SALE: 'UPDATE_SALE',
    DELETE_SALE: 'DELETE_SALE',

    //Products
    FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
    GET_PRODUCT: "GET_PRODUCT",
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',

    //Reports
    FETCH_ALL_SALESBYCONSULTANTS: 'FETCH_ALL_SALESBYCONSULTANTS',
    FETCH_ALL_SALESBYPRODUCTPRICES: 'FETCH_ALL_SALESBYPRODUCTPRICES',
    FETCH_ALL_CONSULTANTSBYFREQUENTLYSOLDPRODUCTS: 'FETCH_ALL_CONSULTANTSBYFREQUENTLYSOLDPRODUCTS',
    FETCH_ALL_CONSULTANTSBYSUMSALES: "FETCH_ALL_CONSULTANTSBYSUMSALES",

    //Global Loader
    USE_GLOBAL_LOADER: "USE_GLOBAL_LOADER",
}